FROM node:20 AS builder

WORKDIR /usr/src

# 의존성 설치
COPY ./package.json ./

# yarn install
COPY yarn.lock ./
RUN yarn
COPY . .

# build
CMD ["yarn", "run", "build"]

FROM node:20-alpine
WORKDIR /usr/src
COPY --from=builder /usr/src ./
CMD [ "yarn" ,"run","start:dev"]
EXPOSE 3000